<?php echo  Yaf\View\Simple::render('common/home.header.phtml');?>
<?php
$static_url = \YaConf::get('MconfInit.global.estatics');
$home = function( $key ) use ( $static_url  ){
	if( $key == 'img' )
		return $static_url.'mango16/home/';
};
?>
<body class="homepage">
		<!-- Header -->
			<div id="header">
				<!-- Inner -->
					<div class="inner">
						<header>
							<h1><a href="#" id="logo">Helios</a></h1>
							<hr />
							<span class="byline">Another fine freebie by HTML5 UP</span>
						</header>
						<footer>
							<a href="#banner" class="button circled scrolly">Start</a>
						</footer>
					</div>
				<!-- Nav -->
					<nav id="nav">
						<ul>
							<li><a href="index.html">Home</a></li>
							<li>
								<span>Dropdown</span>
								<ul>
									<li><a href="#">Lorem ipsum dolor</a></li>
									<li><a href="#">Magna phasellus</a></li>
									<li><a href="#">Etiam dolore nisl</a></li>
									<li>
										<span>And a submenu &hellip;</span>
										<ul>
											<li><a href="#">Lorem ipsum dolor</a></li>
											<li><a href="#">Phasellus consequat</a></li>
											<li><a href="#">Magna phasellus</a></li>
											<li><a href="#">Etiam dolore nisl</a></li>
										</ul>
									</li>
									<li><a href="#">Veroeros feugiat</a></li>
								</ul>
							</li>
							<li><a href="left-sidebar.html">Left Sidebar</a></li>
							<li><a href="right-sidebar.html">Right Sidebar</a></li>
							<li><a href="no-sidebar.html">No Sidebar</a></li>
						</ul>
					</nav>

			</div>

		<!-- Banner -->
			<div id="banner">
				<h2>Hi. You're looking at <strong>Helios</strong>.</h2>
				<span class="byline">
					A (free) responsive site template by <a href="http://www.cssmoban.com/">HTML5 UP</a>.
					Built on <a href="http://skeljs.org">skelJS</a> and released under the <a href="http://www.cssmoban.com/">CCA</a> license.
				</span>
			</div>


		<!-- Carousel -->
			<div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >Website Template</a></div>
            <div class="carousel">
				<div class="reel">

					<article>
						<a href="http://mdomaradzki.deviantart.com/art/Bueller-III-351975087" class="image featured"><img src="<?=$home('img');?>images/pic01.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Pulvinar sagittis congue</a></h3>
						</header>
						<p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
					</article>

					<article>
						<a href="http://mdomaradzki.deviantart.com/art/Disco-351602759" class="image featured"><img src="<?=$home('img');?>images/pic02.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Fermentum sagittis proin</a></h3>
						</header>
						<p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
					</article>

					<article>
						<a href="http://mdomaradzki.deviantart.com/art/The-Patina-of-Time-and-Tide-352128094" class="image featured"><img src="<?=$home('img');?>images/pic03.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Sed quis rhoncus placerat</a></h3>
						</header>
						<p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
					</article>

					<article>
						<a href="http://mdomaradzki.deviantart.com/art/Cityparts-XVIII-350427779" class="image featured"><img src="<?=$home('img');?>images/pic04.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Ultrices urna sit lobortis</a></h3>
						</header>
						<p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
					</article>

					<article>
						<a href="http://mdomaradzki.deviantart.com/art/Vine-Country-381350120" class="image featured"><img src="<?=$home('img');?>images/pic05.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Varius magnis sollicitudin</a></h3>
						</header>
						<p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
					</article>

					<article>
						<a href="http://mdomaradzki.deviantart.com/art/Bueller-III-351975087" class="image featured"><img src="<?=$home('img');?>images/pic01.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Pulvinar sagittis congue</a></h3>
						</header>
						<p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
					</article>

					<article>
						<a href="http://mdomaradzki.deviantart.com/art/Disco-351602759" class="image featured"><img src="<?=$home('img');?>images/pic02.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Fermentum sagittis proin</a></h3>
						</header>
						<p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
					</article>

					<article>
						<a href="http://mdomaradzki.deviantart.com/art/The-Patina-of-Time-and-Tide-352128094" class="image featured"><img src="<?=$home('img');?>images/pic03.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Sed quis rhoncus placerat</a></h3>
						</header>
						<p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
					</article>

					<article>
						<a href="http://mdomaradzki.deviantart.com/art/Cityparts-XVIII-350427779" class="image featured"><img src="<?=$home('img');?>images/pic04.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Ultrices urna sit lobortis</a></h3>
						</header>
						<p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
					</article>

					<article>
						<a href="http://mdomaradzki.deviantart.com/art/Vine-Country-381350120" class="image featured"><img src="<?=$home('img');?>images/pic05.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Varius magnis sollicitudin</a></h3>
						</header>
						<p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
					</article>

				</div>
			</div>

		<!-- Main -->
			<div class="wrapper style2">

				<article id="main" class="container special">
					<a href="http://mdomaradzki.deviantart.com/art/Planet-Bronte-339258500" class="image featured"><img src="<?=$home('img');?>images/pic06.jpg" alt="" /></a>
					<header>
						<h2><a href="#">Sed massa imperdiet magnis</a></h2>
						<span class="byline">
							Sociis aenean eu aenean mollis mollis facilisis primis ornare penatibus aenean. Cursus ac enim
							pulvinar curabitur morbi convallis. Lectus malesuada sed fermentum dolore amet.
						</span>
					</header>
					<p>
						Commodo id natoque malesuada sollicitudin elit suscipit. Curae suspendisse mauris posuere accumsan massa
						posuere lacus convallis tellus interdum. Amet nullam fringilla nibh nulla convallis ut venenatis purus
						sit arcu sociis. Nunc fermentum adipiscing tempor cursus nascetur adipiscing adipiscing. Primis aliquam
						mus lacinia lobortis phasellus suscipit. Fermentum lobortis non tristique ante proin sociis accumsan
						lobortis. Auctor etiam porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum
						consequat integer interdum integer purus sapien. Nibh eleifend nulla nascetur pharetra commodo mi augue
						interdum tellus. Ornare cursus augue feugiat sodales velit lorem. Semper elementum ullamcorper lacinia
						natoque aenean scelerisque.
					</p>
					<footer>
						<a href="#" class="button">Continue Reading</a>
					</footer>
				</article>

			</div>

		<!-- Features -->
			<div class="wrapper style1">

				<section id="features" class="container special">
					<header>
						<h2>Morbi ullamcorper et varius leo lacus</h2>
						<span class="byline">Ipsum volutpat consectetur orci metus consequat imperdiet duis integer semper magna.</span>
					</header>
					<div class="row">
						<article class="4u special">
							<a href="http://mdomaradzki.deviantart.com/art/Bueller-VII-351975126" class="image featured"><img src="<?=$home('img');?>images/pic07.jpg" alt="" /></a>
							<header>
								<h3><a href="#">Gravida aliquam penatibus</a></h3>
							</header>
							<p>
								Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
								porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
							</p>
						</article>
						<article class="4u special">
							<a href="http://mdomaradzki.deviantart.com/art/Home-Bound-Train-II-338912191" class="image featured"><img src="<?=$home('img');?>images/pic08.jpg" alt="" /></a>
							<header>
								<h3><a href="#">Sed quis rhoncus placerat</a></h3>
							</header>
							<p>
								Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
								porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
							</p>
						</article>
						<article class="4u special">
							<a href="http://mdomaradzki.deviantart.com/art/Up-is-Down-325005102" class="image featured"><img src="<?=$home('img');?>images/pic09.jpg" alt="" /></a>
							<header>
								<h3><a href="#">Magna laoreet et aliquam</a></h3>
							</header>
							<p>
								Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
								porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
							</p>
						</article>
					</div>
				</section>

			</div>

		<!-- Footer -->
			<div id="footer">
				<div class="container">
					<div class="row">

						<!-- Tweets -->
							<section class="4u">
								<header>
									<h2 class="icon icon-twitter circled"><span>Tweets</span></h2>
								</header>
								<ul class="divided">
									<li>
										<article class="tweet">
											Amet nullam fringilla nibh nulla convallis tique ante sociis accumsan.
											<span class="timestamp">5 minutes ago</span>
										</article>
									</li>
									<li>
										<article class="tweet">
											Hendrerit rutrum quisque.
											<span class="timestamp">30 minutes ago</span>
										</article>
									</li>
									<li>
										<article class="tweet">
											Curabitur donec nulla massa laoreet nibh. Lorem praesent montes.
											<span class="timestamp">3 hours ago</span>
										</article>
									</li>
									<li>
										<article class="tweet">
											Lacus natoque cras rhoncus curae dignissim ultricies. Convallis orci aliquet.
											<span class="timestamp">5 hours ago</span>
										</article>
									</li>
								</ul>
							</section>

						<!-- Posts -->
							<section class="4u">
								<header>
									<h2 class="icon icon-file circled"><span>Posts</span></h2>
								</header>
								<ul class="divided">
									<li>
										<article class="post stub">
											<header>
												<h3><a href="#">Nisl fermentum integer</a></h3>
											</header>
											<span class="timestamp">3 hours ago</span>
										</article>
									</li>
									<li>
										<article class="post stub">
											<header>
												<h3><a href="#">Phasellus portitor lorem</a></h3>
											</header>
											<span class="timestamp">6 hours ago</span>
										</article>
									</li>
									<li>
										<article class="post stub">
											<header>
												<h3><a href="#">Magna tempus consequat</a></h3>
											</header>
											<span class="timestamp">Yesterday</span>
										</article>
									</li>
									<li>
										<article class="post stub">
											<header>
												<h3><a href="#">Feugiat lorem ipsum</a></h3>
											</header>
											<span class="timestamp">2 days ago</span>
										</article>
									</li>
								</ul>
							</section>

						<!-- Photos -->
							<section class="4u">
								<header>
									<h2 class="icon icon-camera circled"><span>Photos</span></h2>
								</header>
								<div class="row quarter no-collapse">
									<div class="6u">
										<a href="http://mdomaradzki.deviantart.com/art/Air-Lounge-385212062" class="image full"><img src="<?=$home('img');?>images/pic10.jpg" alt="" /></a>
									</div>
									<div class="6u">
										<a href="http://mdomaradzki.deviantart.com/art/Paris-City-Streets-II-382623606" class="image full"><img src="<?=$home('img');?>images/pic11.jpg" alt="" /></a>
									</div>
								</div>
								<div class="row quarter no-collapse">
									<div class="6u">
										<a href="http://mdomaradzki.deviantart.com/art/Trainride-Visions-383309985" class="image full"><img src="<?=$home('img');?>images/pic12.jpg" alt="" /></a>
									</div>
									<div class="6u">
										<a href="http://mdomaradzki.deviantart.com/art/Paris-Metro-382623851" class="image full"><img src="<?=$home('img');?>images/pic13.jpg" alt="" /></a>
									</div>
								</div>
								<div class="row quarter no-collapse">
									<div class="6u">
										<a href="http://mdomaradzki.deviantart.com/art/Cliffs-of-Coogee-II-366961860" class="image full"><img src="<?=$home('img');?>images/pic14.jpg" alt="" /></a>
									</div>
									<div class="6u">
										<a href="http://mdomaradzki.deviantart.com/art/Stormy-Coast-VII-366561367" class="image full"><img src="<?=$home('img');?>images/pic15.jpg" alt="" /></a>
									</div>
								</div>
							</section>
					</div>
					<hr />
<?php echo  Yaf\View\Simple::render('common/home.footer.phtml');?>
