<?php echo  Yaf\View\Simple::render('common/home.header.phtml');?>
<?php
$static_url = \YaConf::get('MconfInit.global.estatics');
$home = function( $key ) use ( $static_url  ){
	if( $key == 'img' )
		return $static_url.'mango16/home/';
};
?>

<section id="services" class="pfblock pfblock-gray">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="pfblock-header wow fadeInUp">
                    <div class="pfblock-subtitle">
                        <h2 class="pfblock-title">What I Do</h2>
												<div class="pfblock-line"></div>
												<ul>
													<li>基于zui的后台管理界面</li>
													<li>引入 laravel 中的 Eloquent</li>
													<li>简单的增删改查实现</li>
													<li>错误捕捉显示及日志记录</li>
													<li>静态资源采用第三方<a href="http://www.qiniu.com/?utm_campaign=baiduSEM&amp;utm_source=baiduSEM&amp;utm_medium=baiduSEM&amp;utm_content=baiduSEM">七牛云</a>托管</li>
													<li>Composer管理包依赖</li>
												</ul>
												<h2 class="pfblock-title">Requirement</h2>
												<div class="pfblock-line"></div>
												<ul >
													<li><a href="http://nginx.org/">Nginx</a></li>
													<li><a href="http://php.net/manual/zh/migration71.new-features.php">PHP 7 +</a></li>
													<li><a href="https://www.zhihu.com/question/41832866">MariaDB</a></li>
													<li><a href="http://pecl.php.net/package/yaconf">YaConf</a></li>
													<li><a href="http://pecl.php.net/package/yaf">Yaf 3.0+</a></li>
													<li><a href="http://www.zui.sexy/#/">Zui 1.5.0</a></li>
													<li><a href="https://lvwenhan.com/laravel/421.html">Eloquent 4.2</a></li>
													<li><a href="http://pkg.phpcomposer.com/">Composer 1.0</a></li>
													</ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <div class="iconbox wow slideInLeft">
                    <div class="iconbox-icon">
                        <span class="icon-magic-wand"></span>
                    </div>
                    <div class="iconbox-text">
                        <h3 class="iconbox-title">自带品牌引导页</h3>
                        <div class="iconbox-desc">解决无自有品牌烦恼，后台自定义更新
</div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="iconbox wow slideInLeft">
                    <div class="iconbox-icon">
                        <span class="icon-puzzle"></span>
                    </div>
                    <div class="iconbox-text">
                        <h3 class="iconbox-title">响应式扁平化设计</h3>
                        <div class="iconbox-desc">用户/代理/管理中心风格全面统一，给你带来最佳的用户体验
</div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="iconbox wow slideInRight">
                    <div class="iconbox-icon">
                        <span class="icon-badge"></span>
                    </div>
                    <div class="iconbox-text">
                        <h3 class="iconbox-title">支付宝在线支付</h3>
                        <div class="iconbox-desc">集成三种支付模式，让你的流量卖得更便捷
</div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="iconbox wow slideInRight">
                    <div class="iconbox-icon">
                        <span class="icon-question"></span>
                    </div>
                    <div class="iconbox-text">
                        <h3 class="iconbox-title">集成云端APP</h3>
                        <div class="iconbox-desc">自动生成带线路管理APP，兼容大部分安卓系统
</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="portfolio" class="pfblock">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="pfblock-header wow fadeInUp">
                    <h2 class="pfblock-title">安装教程</h2>
                    <div class="pfblock-line"></div>
                    <br>
                    <div class="pfblock-subtitle">① 使用下面任意终端软件，连接服务器
</div>
                    <br>
                    <a target="_blank" href="http://rj.baidu.com/soft/detail/15201.html" title="点击下载xshell5" class="btn btn-info">电脑下载Xshell5</a>
                    <a target="_blank" href="http://www.wandoujia.com/apps/com.sonelli.juicessh" title="点我下载橘子ssh" class="btn btn-warning">安卓下载橘子SSH</a>
                    <a target="_blank" href="https://itunes.apple.com/cn/app/id581455211?mt=8" title="点我下载iTerminal" class="btn btn-success">苹果下载iTerminal</a>
                    <div class="pfblock-subtitle">② 执行搭建一键搭建脚本：
</div>
                    <div class="pfblock-subtitle">安装脚本： wget xxx &&bash vpn
</div>
                    <br>
                    <a target="_blank" href="https://github.com/PuShaoWei/Mango16/issues" class="btn btn-danger"> 需要帮助点这里</a>
                    <br>
                    <br>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="alert alert-danger" role="alert">
                                如果提示出错 bash: wget: command not found <br>请执行 yum -y install wget

                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="alert alert-info" role="alert">
                                重启VPN服务：vpn<br>重启lnmp命令：lnmp

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="calltoaction">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-12">
								<h2 class="wow slideInRight" data-wow-delay=".1s">Mango16</h2>
                <div class="calltoaction-decription wow slideInRight" data-wow-delay=".2s">需要您的支持及肯定</div>
            </div>
            <div class="col-md-12 col-lg-12 calltoaction-btn wow slideInRight" data-wow-delay=".3s">
								<a target="_blank" href="https://github.com/PuShaoWei/Mango16" class="btn btn-lg"><i class="fa fa-github fa-fw"></i>来个Start</a>
                <a target="_blank" href="https://github.com/PuShaoWei/Mango16/pulls" class="btn btn-lg"><i class="fa fa-eye fa-fw"></i>一起拯救世界</a>
            </div>
			  </div>
    </div>
</section>
<section class="pfblock" id="skills">
    <div class="container">
        <div class="row skills">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="pfblock-header wow fadeInUp">
                        <h2 class="pfblock-title">更新历史</h2>
                        <div class="pfblock-line"></div>
                        <div class="pfblock-subtitle">2017-03-02
													<ul class="list-group">
														<li>更新完善主页</li>
													</ul>
												</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="testimonials" class="pfblock pfblock-gray">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="pfblock-header wow fadeInUp">
                    <h2 class="pfblock-title">我们的团队</h2>
                    <div class="pfblock-line"></div>
                    <div class="pfblock-subtitle">其实现在就我一个人，欢迎更多小伙伴捧场
</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div id="cbp-qtrotator" class="cbp-qtrotator">
                <div class="cbp-qtcontent">
                    <img src="<?=$home('img');?>images//client-3.jpg" alt="client-1"/>
                    <blockquote>
                        <p>感谢诸位朋友的issue或pull request</p>
                        <footer>@无敌小笼包</footer>
                    </blockquote>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="contact" class="pfblock">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="pfblock-header">
                    <h2 class="pfblock-title">如果你有反馈？</h2>
                    <div class="pfblock-line"></div>
                    <div class="pfblock-subtitle">想要的功能，发现的Bug今天从这里提交！
</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 text-center">
                <a target="_blank" href="javascript:;" class="btn btn-info">SegmentFault</a>
                <a target="_blank" href="javascript:;" class="btn btn-warning">GitHub</a>
            </div>
        </div>
    </div>
</section>
<section id="contact" class="pfblock pfblock-gray">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="pfblock-header">
                    <h2 class="pfblock-title">捐赠支持</h2>
                    <div class="pfblock-line"></div>
                    <div class="pfblock-subtitle">如您觉得我可以做得更好，继续支持我有更好的硬件升级，可以给我捐赠！
</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3 text-center">
                <img src="<?=$home('img');?>images//rcode.jpg" alt="img01" style="width: 220px;"/>
            </div>
        </div>
    </div>
</section>
<?php echo  Yaf\View\Simple::render('common/home.footer.phtml');?>
