<?php
$optionsRender = function($key) use ($options) {
    if (isset($options[$key])) {
        return $options[$key];
    } else {
        return '';
    }
};
?>
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <p class="heart">
                    免责声明：我所有产品/脚本只用于交流研究 严禁用于一切非法业务请自觉遵守中华人民共和国法律 一切法律责任与本人以及团队无关<br>
                    © 2016 - 2017 mango16.cc . 闽ICP备16024731号-13
<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1261667908'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1261667908%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
                </p>
            </div>
        </div>
    </div>
</footer>
<div class="scroll-up">
    <a href="#home">
        <i class="fa fa-angle-up  fa-2x"></i>
    </a>
</div>
</body>
</html>

<?php echo library\Core\Tools::script($optionsRender('script'));?>
