<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<!-- dns prefetch -->
<meta http-equiv="x-dns-prefetch-control" content="on" />
<link rel="dns-prefetch" href="//static.sporte.cn" />

<!-- Set render engine for 360 browser -->
<meta name="renderer" content="webkit">

<!-- Cache -->
<meta content="no-cache,must-revalidate" http-equiv="Cache-Control">
<meta content="no-cache" http-equiv="pragma">
<meta content="0" http-equiv="expires">

<!-- ICON -->
<link rel="icon" type="image/png" href="/">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="<?php echo library\Base\NoCSRF::generate( 'csrf_token' );?>" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">


