<?php

$optionsRender = function($key) use ($options) {
	if (isset($options[$key])) {
		return $options[$key];
	} else {
		return '';
	}
};

?>
<!DOCTYPE html>
<html lang="en">
<head>
  <?php echo Yaf\View\Simple::render('common/admin.meta.phtml'); ?>
  <meta name="description" content="<?php echo $optionsRender('description')?>">
  <meta name="keywords" 	 content="<?php echo $optionsRender('keywords')?>">
  <title><?php echo $optionsRender('title')?></title>
  <?php echo library\Core\Tools::style($optionsRender('style'));?>
</head>
<body>
